const Client = require("./structures/client")
const Commands = require(`./Handlers/commands`)
const Events  = require(`./Handlers/commands`)
const config = require("../config.json")
const client = new Client(config.client_Options)
client.run(Events, Commands, config.token)
console.log(`initializing Discord bot`)