'use strict';
exports.__esModule = true;
var client_1 = require("./structures/client");
var commands_1 = require("./Handlers/commands");
var events_1 = require("./Handlers/events");
var config_json_1 = require("../config.json");
var path_1 = require("path");
var client = new client_1["default"](path_1.normalize(__dirname + "/."), {});
console.log("initializing Discord bot");
client.start(events_1["default"], commands_1["default"], config_json_1["default"].token);
["uncaughtException", "warning", "unhandledRejection"].forEach(function (p) { return process.on(p, console.error); });
